language: ruby

rvm: 
 - 2.5.1

services:
  - postgresql

cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create

script:
  - bundle exec rake test
