name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    services:
      db:
        image: postgres:9
        ports: ['5432:5432']
        env:
          POSTGRES_USER: sharecar
          POSTGRES_PASSWORD: sharecar
          POSTGRES_DATABASE: sharecar-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Install libpg
      run: |
        sudo apt-get -yqq install libpq-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Run test
      run: |
        bundle exec rake db:setup
        bundle exec rake test
    - name: Run assets:precompile
      run: |
        bundle exec rake assets:precompile
    - name: Run slim-lint
      run: bundle exec slim-lint app/views
