name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    services:
      db:
        image: postgres:9
        ports: ['5432:5432']
        env:
          POSTGRES_USER: sharecar
          POSTGRES_PASSWORD: sharecar
          POSTGRES_DATABASE: sharecar-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Install libpg
      run: |
        sudo apt-get -yqq install libpq-dev
    - uses: masa-iwasaki/setup-rbenv@v1
    - uses: actions/checkout@master
    - name: Cache RBENV_ROOT
      uses: actions/cache@v2
      id: cache_rbenv
      with:
        path: /home/runner/.rbenv
        key: ${{ runner.os }}-rbenv-${{ hashFiles('**/.ruby-version') }}
        restore-keys: |
          {{ runner.os }}-rbenv-
    - name: Install Ruby
      run: |
        eval "$(rbenv init -)"
        rbenv install -s `cat .ruby-version`
    - name: Cache vendor/bundle
      uses: actions/cache@v2
      id: cache_vendor_bundle
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          {{ runner.os }}-gems-
    - name: Build
      run: |
        eval "$(rbenv init -)"
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run rubocop
      run: |
        eval "$(rbenv init -)"
        bundle exec rubocop
    - name: Run test
      run: |
        eval "$(rbenv init -)"
        bundle exec rake db:setup
        bundle exec rake test
    - name: Run assets:precompile
      run: |
        eval "$(rbenv init -)"
        bundle exec rake assets:precompile